//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApplication1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HL     J  Fj
        ///BBBBBBBBBBBBB
        ///JASON_LY
        ///On October 8, 2015 around 11:00 PM, Jason Ly was writing a hangman program.
        ///While writing his hangman program, Jason was hit with divine inspiration from
        ///the god of hangman. Upon receiving his inspiration, Jason wrote &quot;Hungman.&quot;
        ///Because Jason felt that Hungman was the will of the gods,
        ///Jason safeguarded Hungman with his life. While Jason being inspired,
        ///he was taught by the gods to duplicate himself. He used his duplicates
        ///to help him protect Hungman from the rest of the  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _0 {
            get {
                return ResourceManager.GetString("_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HUNGMAN
        ///JASON_LY
        ///Levi starts up his computer to play his new copy
        ///of Hungman.
        ///
        ///Upon starting his computer, he cuts and pastes his
        ///copy of Hungman into his email and sends it to himself.
        ///
        ///Levi proceeds to play Hungman on his phone.
        ///
        ///Press any key to continue...
        ///JASON_LY
        ///Controls:
        ///Any letter a-z: Guess
        ///
        ///Finish the game of Hungman.
        ///
        ///Press any key to continue....
        /// </summary>
        internal static string _1 {
            get {
                return ResourceManager.GetString("_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                 j jF
        ///        j    JFBBBBB                        j   F
        ///HL   BBBBBBBBBB     B   JF    jFBBBBBBBBBBBBBBBBB
        ///BBBBB                BBBBBBBBBBB
        ///JASON_LY
        ///Levi has now successfully played a copy of Hungman.java,
        ///but Levi now realizes that he cannot copy and paste on his
        ///computer because he replaced his keyboard and mouse with
        ///his Street Fighter V fight stick. As a result, Levi must 
        ///return to his adventure to capture more copies of hungman
        ///so that the world may play Hungman.
        ///
        ///Press any key to contin [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2 {
            get {
                return ResourceManager.GetString("_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HL                BBB
        ///BBBBBBBBBBB BBBBB    B
        ///           BFFFFFJFFFFFB  
        ///           BBBBBBBBBBBBBB
        ///JASON_LY
        ///D = 2
        ///After distributing those copies of Hungman to his a select few,
        ///Levi wants more copies of Hungman. Levi searches near and far
        ///for 10 more copies, but fails to find any. As a result, Levi
        ///travels to Jason&apos;s room where Jason keeps his copies.
        ///
        ///Press any key to continue...
        ///JASON_LY
        ///Upon finding Jason&apos;s room, Levi is confronted by the real Jason!
        ///Levi prepares to fight Jason so that he can capture th [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _3 {
            get {
                return ResourceManager.GetString("_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bed {
            get {
                object obj = ResourceManager.GetObject("bed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap black {
            get {
                object obj = ResourceManager.GetObject("black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap blue_circle {
            get {
                object obj = ResourceManager.GetObject("blue_circle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap computer {
            get {
                object obj = ResourceManager.GetObject("computer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap face {
            get {
                object obj = ResourceManager.GetObject("face", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap green_circle {
            get {
                object obj = ResourceManager.GetObject("green_circle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap grey {
            get {
                object obj = ResourceManager.GetObject("grey", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hungman_java {
            get {
                object obj = ResourceManager.GetObject("hungman_java", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap json {
            get {
                object obj = ResourceManager.GetObject("json", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap json_station {
            get {
                object obj = ResourceManager.GetObject("json_station", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   wwwww 
        ///www   w 
        ///wgcb  w 
        ///www bgw 
        ///wgwwb w 
        ///w w g ww
        ///wb Bbbgw
        ///w   g  w
        ///wwwwwwww.
        /// </summary>
        internal static string level1 {
            get {
                return ResourceManager.GetString("level1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      wwww  
        ///wwwwww  w  
        ///w  b   cw  
        ///w  w ww ww 
        ///ww wgg   w 
        /// w  ggwwbw 
        /// wbww ww ww
        /// w    b   w
        /// w  www   w
        /// wwww wwwww.
        /// </summary>
        internal static string level2 {
            get {
                return ResourceManager.GetString("level2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wwwwwww
        ///w w   w
        ///w cbb w
        ///w b   w
        ///w ggg w
        ///wwwwwww.
        /// </summary>
        internal static string level3 {
            get {
                return ResourceManager.GetString("level3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap levi {
            get {
                object obj = ResourceManager.GetObject("levi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream pew1 {
            get {
                return ResourceManager.GetStream("pew1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream pew2 {
            get {
                return ResourceManager.GetStream("pew2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream vroom {
            get {
                return ResourceManager.GetStream("vroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;A&quot;,&quot;ABILITY&quot;,&quot;ABLE&quot;,&quot;ABOUT&quot;,&quot;ABOVE&quot;,&quot;ABSENCE&quot;,&quot;ABSOLUTELY&quot;,&quot;ACADEMIC&quot;,&quot;ACCEPT&quot;,&quot;ACCESS&quot;,&quot;ACCIDENT&quot;,&quot;ACCOMPANY&quot;,&quot;ACCORDING&quot;,&quot;ACCOUNT&quot;,&quot;ACHIEVE&quot;,&quot;ACHIEVEMENT&quot;,&quot;ACID&quot;,&quot;ACQUIRE&quot;,&quot;ACROSS&quot;,&quot;ACT&quot;,&quot;ACTION&quot;,&quot;ACTIVE&quot;,&quot;ACTIVITY&quot;,&quot;ACTUAL&quot;,&quot;ACTUALLY&quot;,&quot;ADD&quot;,&quot;ADDITION&quot;,&quot;ADDITIONAL&quot;,&quot;ADDRESS&quot;,&quot;ADMINISTRATION&quot;,&quot;ADMIT&quot;,&quot;ADOPT&quot;,&quot;ADULT&quot;,&quot;ADVANCE&quot;,&quot;ADVANTAGE&quot;,&quot;ADVICE&quot;,&quot;ADVISE&quot;,&quot;AFFAIR&quot;,&quot;AFFECT&quot;,&quot;AFFORD&quot;,&quot;AFRAID&quot;,&quot;AFTER&quot;,&quot;AFTERNOON&quot;,&quot;AFTERWARDS&quot;,&quot;AGAIN&quot;,&quot;AGAINST&quot;,&quot;AGE&quot;,&quot;AGENCY&quot;,&quot;AGENT&quot;,&quot;AGO&quot;,&quot;AGREE&quot;,&quot;AGREEMENT&quot;,&quot....
        /// </summary>
        internal static string words {
            get {
                return ResourceManager.GetString("words", resourceCulture);
            }
        }
    }
}
